listener 1883

allow_anonymous false

password_file /etc/mosquitto/passwd

persistence true
persistence_location /var/lib/mosquitto/
retained_persistence true

persistent_client_expiration 1d

log_type all
log_dest stdout
log_timestamp true